# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c38e9fad6e9f173409994e54687128fe4d6e6791c79f0c67959f6d285fc793cc6d3fe3e7e366e196b00aadc68ff36ca6aa2a5162cb66ae0546e61f9631dee19

test:
  secret_key_base: 9821407214870e39bdaa0af3c84d969aac8298b875db070f01c9c62988e5b6d8feb0676000ae8153c663851f60d38ac4c80130c54c2ace31ea7bcead42f83ab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
